### PR TITLE
code quality changes, simple build script

### PR DESCRIPTION
**Pull request by dmig**
I'll start my series of pull requests with this one. It doesn't change anything, just addresses overall code quality:
- fix 1 console warning about undefined variable
- fix bunch of linter warnings
- add ESLint config for code checking

Also I added simple script to update translation template, translation files from new template and compile setting schema.

### CODE REVIEW

**Comment by Tudmotu** [comment]
Hi @dmig, thank you very much for the effort and this PR! :smiley: 
Unfortunately, I prefer not incorporating of these changes. ESList is not something I want to use, and the stylistic changes to the code are partly nice and partly not my taste.

I really like the ``build.sh`` script you added, though I would rename it something more appropriate (like ``build-translations.sh``).

If you could open a PR for the build script on its own (and rename it), that would be awesome :grin:
I can also just cherry-pick it, if you don't feel like making another PR.

And again, thanks for the effort!

**Comment by dmig** [comment]
These "stylistic" changes are for code to comply to official style guide: https://wiki.gnome.org/Projects/Gjs/StyleGuide
You may use ESLint or may not, but it's config will allow anyone to keep same coding style.

**Comment by dmig** [comment]
Current `build.sh` is a bit dirty solution, it will update `.pot` and `.mo` files on every run. So I consider it's a temporary tool. It'd be better to check if `.pot` is changed in any line other than `POT-Creation-Date`. 
Also `.po` and `gschemas.compiled` may be excluded from repository, as they are generated.

**Comment by Tudmotu** [comment]
Yeah, the main issue with "style guides" and tools like ESlint is that they inevitably cause discussions on what is the "right" way to write code. I believe every way is "right", and I don't want to limit people to a specific style. If you would like discussing this further and hear more on my views, we can do this via email :)

Regarding the "compile .pot file every build" - that's not necessarily bad. Nowadays every change causes the translations to move from one line to another, so it's even appropriate to update the translation before every release. We can also add a ``build.sh`` script that runs the ``build-translations.sh`` and then ``bundle.sh`` to prepare for release. And in the utopian future where we have gnome-shell tests, it will also run ``run-tests.sh`` :smile:

**Comment by dmig** [comment]
I think as far as we develop for Gnome Shell, we should follow it's developers guides. That's all.
Especially when they provide reasonable guides.

**Comment by Tudmotu** [comment]
I am closing this PR. I might cherry pick that script some when tho :)

**Pull request closed without merging**
