### PR TITLE
Private mode

### PR DESCRIPTION
**Pull request by RaphaelRochet**
For #29

### CODE REVIEW

**Comment by Tudmotu** [comment]
Didn't test yet, but going over the code, I see on line 335, you use ``firstMenuItem``. The last selected entry before entering into private mode isn't necessarily the first one. But I'm not sure if it's that important actually.. What do you think?

Also, thank you very much for this! I'll test it and probably merge. :)

**Comment by RaphaelRochet** [comment]
You're right. Instead of firstMenuItem we should use the selected item ! Let me fix this before merging.

**Comment by RaphaelRochet** [comment]
There.

**Comment by Tudmotu** [comment]
I modified some stuff, mainly removed the custom icons in favor of CSS styling.
You can check it out and let me know if it still works as you expect :)

I'll probably test it some more later today and then merge.

Again, thanks!

**Comment by RaphaelRochet** [comment]
Looks nice. I like the CSS way.
Sorry I messed up my repo and lost the pull request. Hopefully I could merge back you feature branch !

**Comment by Tudmotu** [comment]
Yeah sure, no problem. I already have your changes, and pushed them to branch ``feature/private-mode``. I believe that when I merge it to master, it will appear here. :)

**Comment by Tudmotu** [comment]
Uploaded to e.g.o.
Thank you @RaphaelRochet! :D

**Pull request closed without merging**
