### PR TITLE
Completely rewrite all core logic using compacting log storage

### PR DESCRIPTION
**Pull request by SUPERCILEX**
This has been released in a rewritten version of the extension: https://extensions.gnome.org/extension/4839/clipboard-history/, https://github.com/SUPERCILEX/gnome-clipboard-history.

Here's what's been fixed:
- #229
- #164
- #127
- #91
- #337
- #158
- #269
- #162
- #174
- #176
- #326
- #322
- #222
- #290
- #109
- #278
- #267
- #263
- #188
- #186
- #187
- #175
- #80
- #131
- #117
- #55
- #79
- #281
- #291
- #238
- #153
- #231
- #116
- #336
- #318
- #191
- #303
- #8
- #248
- #251

### CODE REVIEW

**Comment by jacksongoode** [comment]
Could you provide some summary of the improvements of this PR?

**Comment by SUPERCILEX** [comment]
Depending on how things go, these changes will either be part of this repo or I'll publish my own version of clipboard indicator. In either case, I'll make announcements on Reddit and write a blog post about the compacting log, fast hashing, and other optimizations once everything is ready. You can track my progress here if you're interested: https://github.com/SUPERCILEX/gnome-shell-extension-clipboard-indicator/commits/master.

The gist of these changes is relatively straightforward: make everything go fast, remove all scaling limitations, make the code more maintainable, and implement useful feature requests where possible.

**Comment by lgg** [comment]
@SUPERCILEX please open issues tab on your's fork page.

**Comment by SUPERCILEX** [comment]
Done!

And actually, since I'd like to close some tabs, here are the relevant issues being worked on from this repo:
- Fixed: #229, #164, #127, #91, #337, #158, #269, #162, #174, #176, 
- To be implemented: #291 (with [this](https://github.com/farzher/fuzzysort/blob/master/fuzzysort.js)), #238, #231 (and transitively #116), #336, and copying arbitrary mime types (unless that turns out to be really hard) (resources: [this](https://github.com/neffo/bing-wallpaper-gnome-extension/blob/master/thumbnail.js) and [this](https://github.com/cinatic/gnome-shell-extension-neingag) for displaying images)
- To be implemented maybe: #110, #251, #248

**Comment by SUPERCILEX** [comment]
Also, would you two be willing to do some QA? I can let you know once I'm ready and post instructions here on how to install the updated extension.

**Comment by SUPERCILEX** [comment]
cc @b00f who might be interested, I've seen your name pop up a bunch

**Comment by jacksongoode** [comment]
Sure, I've already been using your build for a few days actually! It does feel a little snappier, but there's this interesting lag that still exists when toggling the extension and then hovering over the system menu and back to indicator. This lag existed in the upstream as well but I was wondering if your changes had addressed it.

**Comment by SUPERCILEX** [comment]
Hmmm, not sure what you mean. As in, you put your mouse over the clipboard icon and then move it to the wifi icon?

**Comment by jacksongoode** [comment]
Yes, exactly - while the popup is toggled, so switching from the system dropdown (volumne, mic, brightness, etc.) to the clipboard dropdown causes some stuttering as the history loads.

**Comment by SUPERCILEX** [comment]
Ohhhhhh, I think I have a guess for what's going on! We only build the menu UI after loading all the items, and since that takes a while you won't see anything for a bit. Will take a look later and let you know if that's it.

**Comment by SUPERCILEX** [comment]
@jacksongoode the slow start issue should be fixed. :tada:

**Comment by luisalvarado** [comment]
Jesus christ am just seeing this. Can you please tell me what type of coffee you drank to do this much work. Just amazing!

**Pull request closed without merging**
