### PR TITLE
ScrollView clip to allocation

### PR DESCRIPTION
**Pull request by b00f**
Clip the scroll view to the content.

### CODE REVIEW

**Comment by RaphaelRochet** [comment]
I don't see any effect of `clip_to_allocation: true`, what is it for ?

**Comment by b00f** [comment]
It clips the content of scroll-view to the allocated area. You might scroll down and up, then click the top-bar icon. Sometimes the scroll view pick wrong item which is not inside the allocated area.

**Comment by RaphaelRochet** [comment]
Oh ok thanks for the explanation

**Comment by b00f** [comment]
I searched a lot to find the solution. That is really bad of gnome developers. A simple thing but big effect.

**Comment by b00f** [comment]
May I know why you close this PR?

**Comment by Tudmotu** [comment]
What does it fix exactly? Can you share steps to reproduce? A screenshot?
Also, is there an open issue about it?

**Comment by b00f** [comment]
I think comments on this PR are clear enough:

> Oh ok thanks for the explanation

> I searched a lot to find the solution. That is really bad of gnome developers. A simple thing but big effect.

Forget it. Let it be!

**Pull request closed without merging**
