### PR TITLE
Add gnome 3.20 support

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**

### CODE REVIEW

**Comment by Tudmotu** [comment]
Thanks! :)

**Comment by bil-elmoussaoui** [comment]
Can you update the extension on extensions.gnome.org ?

**Comment by Tudmotu** [comment]
I uploaded a version, but it will need to be approved since it contains some more changes. Hopefully it'll take a day or two.

**Comment by Tudmotu** [comment]
New version is available on e.g.o :)

**Pull request merged**
