### PR TITLE
Updated Czech translation

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by Tudmotu** [comment]
Nice, thanks!! :)

**Comment by AsciiWolf** [comment]
@Tudmotu I see you did not merge it yet. Is there any problem with my PR?

**Comment by Tudmotu** [comment]
Nope, just forgot to click it :wink:

**Comment by AsciiWolf** [comment]
@Tudmotu It looks like that the "Type here to search...", "Icon", "Clipboard Content" and "Both" translations are not applied for some reason. Do you have any idea what could be the issue?

**Comment by AsciiWolf** [comment]
That's weird, "Type here to search..." is now correctly translated after a reboot, but the other strings are still untranslated.

**Comment by Tudmotu** [comment]
Thanks, @AsciiWolf - seems like these are not actually using the gettext function:
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/blob/master/prefs.js#L205

**Pull request merged**
