### PR TITLE
Italian translation fixed + added dropdown arrow

### PR DESCRIPTION
**Pull request by amivaleo**
Hi!
I fixed the italian translation. There was a typo in it in the word "characters" which, in the italian version, was written in french. That was my mistake: I made the translation starting from french.

I also added the dropdown arrow to che icon on the top panel. It's just for consistency with the other menus which have that arrow. I don't like it, but I think it should be put there.
It's just a single line of code inside extension.js. Check it! :)

I hope you will appreciate this contributions!

### CODE REVIEW

**Comment by Tudmotu** [comment]
Hi!
Thanks, for the translation and also the arrow :)
I think you forgot to commit the changes to the .po file? I only see that the .mo file changed
Can you please update this PR? thanks!

**Comment by amivaleo** [comment]
Oh, I'm sorry!
I've just uploaded the .po file in my branch. Do I have to make another pull request or it's automatically updated?

**Comment by Tudmotu** [comment]
It automatically updates here :)
Thanks! That was fast :D

**Comment by amivaleo** [comment]
No problem. :)

**Pull request merged**
