### PR TITLE
Support for synchronizing PRIMARY and CLIPBOARD clipboards

### PR DESCRIPTION
**Pull request by dankeder**
First of all, thank you for this extension - so far it's the best clipboard manager for Gnome I have tried, very simple and easy to use. 

However I missed one feature I was very used to - synchronizing contents of PRIMARY and CLIPBOARD clipboards. I tried to implement it myself. Because making Gnome extensions is not really my turf suggestions are very welcome.

By default the feature it is turned off, it can by turned on using a toggle "Synchronize selection and clipboard"  in extension settings I have been testing it for about a week and it seems to be working well.

Related issues:
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/8
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/227

### CODE REVIEW

**Comment by Tudmotu** [comment]
Thank you for this PR.
I really want to be able to review it but since you modified the PO files, there are no conflicts.
Can you please revert the changes you made to the PO files and push a version without the conflicts?

Thank you :pray:

**Comment by dankeder** [comment]
Ok, I removed changes to locale files.

**Comment by Tudmotu** [comment]
Thank you! :pray:

**Comment by Tudmotu** [comment]
I know this PR is ancient but still wanted to say I really appreciate the time and effort that was put into making these changes.

Since GNOME 45 is backward-incompatible, the extension had to be refactored and so this PR will not be relevant anymore. But on the other hand, I hope it would make it easier to implement this feature in the future.

The new version is available under the `gnome45` branch for now:
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/tree/gnome45

**Pull request closed without merging**
