### PR TITLE
Bump supported shell to 44

### PR DESCRIPTION
**Pull request by cewbdex**
I have tested it on my system and it works.

### CODE REVIEW

**Comment by biplab-khalti** [comment]
@cewbdex Also bump the `version` to 45 in `metadata.json`.

**Comment by Tudmotu** [comment]
Thank you for testing it out. Merged, and will upload to e.g.o soon.

**Comment by Tudmotu** [comment]
Uploaded to e.g.o :slightly_smiling_face:

**Comment by Sherlock-Holo** [comment]
@Tudmotu could you create a new git tag to release a new version?
I notice the AUR use the git tag as the package version

**Comment by Tudmotu** [comment]
@Sherlock-Holo It should already be tagged:
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/releases/tag/v45

**Pull request merged**
