### PR TITLE
Update clipboard-indicator.po

### PR DESCRIPTION
**Pull request by Etamuk**
Also the clipboard-indicator.mo file as zip (cannot upload it here directly):
[clipboard-indicator.zip](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/files/3717336/clipboard-indicator.zip)

### CODE REVIEW

**Comment by Tudmotu** [comment]
To update the .mo file, run the `compile-locales.sh` script, and commit the change.

**Comment by Tudmotu** [comment]
I merged and updated the .mo files. Thanks !

**Comment by Etamuk** [comment]
Thank you. I don't know much about programming. But I am good in translating ENG > DE. :-) 
When translating I always take the source file with the strings directly from the project page. 
I can not downloading the source and uploading it back to the branch again. I do not know enough about it. So sorry for that. For the most translation I am working on the .mo file is not needed.

**Comment by Tudmotu** [comment]
That's ok, translating is already a great help - thanks! :)

**Pull request merged**
