### PR TITLE
Able to select item by the keyboard events

### PR DESCRIPTION
**Pull request by b00f**
Fixing #156.

Please test it before merge. I brought out the Set ad Get clipboard functions to Utils for ease of debugging.
The `activate` event worked fine. The problem was inside `_onMenuItemSelected` which was duplicated with `_onMenuItemSelectedAndMenuClose`.

### CODE REVIEW

**Comment by b00f** [comment]
May I know why you close this PR?

**Comment by Tudmotu** [comment]
I could not reproduce it.
Please check the latest version of the extension - it works

**Comment by Tudmotu** [comment]
Also, this PR again contains unrelated changes.
If you want to have a better chance of getting a PR accepted, stop making unrelated changes.
Only change the code that you need. Don't refactor anything without consulting with me.

**Comment by b00f** [comment]
I do remember we have discussed about this change before. Looks ate the #156. It is still open.
I didn't change any code without discussing with you. 
Since you didn't check this PR for quit long time, you probably have forgotten about the way I fixed it.

**Pull request closed without merging**
