### PR TITLE
Using Notify for notifications

### LINKED ISSUE #26: Use GJS Notification (Notify)
Please use GJS Notify to send notifications! 
More informations [here](https://wiki.archlinux.org/index.php/Desktop_notifications)

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
Fixes #26
Looks better now
screenshot from 2016-01-15 14-34-25

### CODE REVIEW

**Comment by Tudmotu** [comment]
Thanks!
But note that ``_showNotification()`` is also called from ``_previousEntry()`` and ``_nextEntry()`` methods.
Maybe leave the ``_showNotification()`` method, but re-implement it with ``Main.notify()``?

**Comment by bil-elmoussaoui** [comment]
Didn't notice that, Done!

**Comment by Tudmotu** [comment]
First of all, thank you very much for your contributions :)
Though after checking this PR, I have two issues with using the notification mechanism:
# Notifications appear and persist in the gnome notification box (when clicking on the date). This feels a bit weird for me, cause these are not notifications I need to see in future.. Can we somehow not persist these notifications?
# When changing several entries rapidly using the shortcuts, the next notifications won't appear until the first notification times-out and disappears. We need to remove previous notifications when a new one comes in, but I'm not sure how to do that.

@bil-elmoussaoui, @RaphaelRochet, what do you guys think?

**Comment by RaphaelRochet** [comment]
Hi to fix the first you simply have to set transiant off.
For the 2 you should update the previous notification.

**Comment by RaphaelRochet** [comment]
Please look at how I made it in the arch-update extension. Hope the code is readable :
https://github.com/RaphaelRochet/arch-update
```
_showNotification: function(message) {
		if (this._notifSource == null) {
			// We have to prepare this only once
			this._notifSource = new MessageTray.SystemNotificationSource();
			this._notifSource.createIcon = function() {
				return new St.Icon({ icon_name: 'arch-lit-symbolic' });
			};
			// Take care of note leaving unneeded sources
			this._notifSource.connect('destroy', Lang.bind(this, function() {this._notifSource = null;}));
			Main.messageTray.add(this._notifSource);
		}
		let notification = null;
		// We do not want to have multiple notifications stacked
		// instead we will update previous
		if (this._notifSource.notifications.length == 0) {
			notification = new MessageTray.Notification(this._notifSource, _('New Arch Linux Updates'), message);
			notification.addAction( _('Update now') , Lang.bind(this, function() {this._updateNow()}) );
		} else {
			notification = this._notifSource.notifications[0];
			notification.update(_('New Arch Linux Updates'), message, { clear: true });
		}
		notification.setTransient(TRANSIENT);
		this._notifSource.notify(notification);
	},
```

**Comment by bil-elmoussaoui** [comment]
@RaphaelRochet Can i use a part of your code? :+1:

**Comment by RaphaelRochet** [comment]
That's what open source is made for ;) Feel free to use it.

**Comment by bil-elmoussaoui** [comment]
Finally had the time to update this! Should work fine now :+1:

**Comment by Tudmotu** [comment]
Thank you very much! :smile: 
Code looks good. I'll check it out soon, then probably merge. :)

**Comment by bil-elmoussaoui** [comment]
You're welcome! Is there something else i need to update to see this merged ? :D

**Pull request merged**
