### PR TITLE
Add 42 as it works there too

### PR DESCRIPTION
**Pull request by shemgp**
Tested on Ubuntu Jammy + GNOME PPA with gnome-shell 42~alpha.

Preferences works too.

Thanks for this nice and useful extension.

### CODE REVIEW

**Comment by VitalyAnkh** [comment]
I don't think it works on Gnome 41. See https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/342.

**Comment by SUPERCILEX** [comment]
Hey, I just published a re-written version of this extension: https://github.com/SUPERCILEX/gnome-clipboard-history. Would either of you be able to try it on 42 and report back if it works?

**Comment by VitalyAnkh** [comment]
@SUPERCILEX I tried it and it works great on Gnome 42 (build with the latest source code of gnome-shell and gjs). Thanks!

**Comment by shemgp** [comment]
@SUPERCILEX Tested with gnome-shell 42.beta, gjs 1.71.1, and mozjs 91.6.0, and it works for me too. I had to add 42 to the metadata.json.

**Comment by Tudmotu** [comment]
Closing in favor of #348

**Pull request closed without merging**
